# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'

# Dracula theme settings
set -g @dracula-show-powerline true
set -g @dracula-plugins "git time"
set -g @dracula-show-left-icon session
set -g @dracula-time-format "%H:%M"

# Terminal colors
set -g default-terminal "screen-256color"

# Initialize TPM (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'
